spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=dpr9t2kxo
cloudinary.api_key=537429854688371
cloudinary.api_secret=AeeYkiMFVQgY3V4nk8z2PChKvJ0
